name: LinkGrabber

on:
  schedule:
    - cron: '*/60 * * * *'

  pull_request:
    branches: [ main ]

  workflow_dispatch:
jobs:

  runCode:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Grab Link

        run: |
          git log -1 --pretty=format:'%an'
          git log -1 --pretty=format:'%ae'
          git config --global user.name "$(git log -1 --pretty=format:'%an')"
          git config --global user.email "$(git log -1 --pretty=format:'%ae')"
          git config --list
          #git config --global user.email "wh-ge@hll.localhost"
          #git config --global user.name "wh-ge"
          chmod +x exec_grabber.sh && ./exec_grabber.sh
          git add -A
          git commit -m "./youtubeLink.txt is updated."
          git push
