name: LinkGrabber
        
on:
  schedule:
    - cron: '*/60 * * * *'

  pull_request:
    branches: [ main ]

  workflow_dispatch:
  
env:
  GH_USERNAME: ${{ github.actor }}

jobs:

  runCode:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Grab Link
      

        run: |
          git config --global user.name "${GH_USERNAME}"
          git config --global user.email "${GH_USERNAME}@users.noreply.github.com"
          git config user.name
          git config user.email
          chmod +x exec_grabber.sh && ./exec_grabber.sh
          git add -A
          git commit -m "./youtubeLink.txt is updated."
          git push

